### ISSUE TITLE
Password field support

### ISSUE THREAD

**Issue by danielgwood** [danbentley/placeholder#3]
I'll admit I haven't actually tested it, but from a look through of your code, it doesn't look like password inputs are supported, since all you do is put the placeholder text in the value attribute of each form element.

Similar plugins by others have done this by switching the type, or inserting labels over the top of the password elements.

**Comment by danbentley** [comment]
Hi danielgwood,

You're right, password fields yet aren't supported. 

As csswizardry commented: "we thought it more pragmatic to deliver a bog-standard experience on password fields rather than bloating/altering the code to fully cater for an edge case." 

https://github.com/danbentley/placeholder/pull/1#issuecomment-1242169

Although, I have to say, the programmer in me is irritated by the fact the plugin doesn't support password fields. I haven't had chance to look into the issue, but I'd like to add support in the future.
